// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/index.tsx';
import * as $1 from './routes/word/[sentenceId]/[wordId].tsx';
import * as $$0 from './islands/InputMask.tsx';
import * as $$1 from './islands/RandomizedButton.tsx';

const manifest = {
    routes: {
        './routes/index.tsx': $0,
        './routes/word/[sentenceId]/[wordId].tsx': $1,
    },
    islands: {
        './islands/InputMask.tsx': $$0,
        './islands/RandomizedButton.tsx': $$1,
    },
    baseUrl: import.meta.url,
};

export default manifest;
